### ISSUE TITLE
Support for API with key?

### ISSUE THREAD

**Issue by stevesbrain** [benapetr/stikkit#3]
At the moment, I haven't seen anything so suggest this supports the API with a key. Am I mistaken, or if not, are there any plans for this? Thanks!

**Comment by benapetr** [comment]
Sorry I totally overlooked this, what do you actually mean? Can you give me some examples?

**Comment by seitzbg** [comment]
You need to include an API key in the form of ?apikey=KEY when you are creating a paste now.

**Comment by stevesbrain** [comment]
Thanks @seitzbg - I'd totally forgotten I'd even created this issue :) I'm presuming changes have been made in the code since I initially queried (as you've indicated) - so I trust this is resolved now. I'll close the issue and take a look - thanks!

**Comment by seitzbg** [comment]
No... I mean it's not fixed yet, I was replying to benapetr ! :)

**Comment by stevesbrain** [comment]
Ah, my apologies :) I've just taken a look, and the upstream fork Pitriss/stikkit actually adds API key support in commit 14ad63b

Just in case you're looking to get it going as well, I've added some doco in my fork (stevesbrain/stikkit) in commit c2aa1ca just so it's clear what configs do what. I've tested and all is working - not sure if @benapetr is still actively working on this project or not, so not sure if the upstream PR will end up being accepted.

**Comment by seitzbg** [comment]
Thanks Steve!

On Sun, Oct 25, 2015 at 10:30:59PM -0700, Steve Divskinsy wrote:
> Ah, my apologies :) I've just taken a look, and the upstream fork Pitriss/
> stikkit actually adds API key support in commit 14ad63b
> 
> Just in case you're looking to get it going as well, I've added some doco in my
> fork (stevesbrain/stikkit) in commit c2aa1ca just so it's clear what configs do
> what. I've tested and all is working - not sure if @benapetr is still actively
> working on this project or not, so not sure if the upstream PR will end up
> being accepted.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
             
Bryan G. Seitz

**Comment by benapetr** [comment]
Sorry guys, I totally overlooked this, github should be more loud about these changes :/ I merged your pull request now

**Comment by framawiki** [comment]
Is it fixed now ?
